### ISSUE TITLE
White Corners on Cards

### ISSUE THREAD

**Issue by lancesafranek** [sjsafranek/mtghordesurvival#1]
Corners of cards have white bits. Very noticeable on black background.

**Comment by sjsafranek** [comment]
this might be a little difficult to fix. It appears to be on the image itself:
https://img.scryfall.com/cards/normal/front/8/f/8f8a75da-ea3c-43e7-9d32-1c92f8ec0fd2.jpg?1562928849

**Comment by sjsafranek** [comment]
adding a border-radius to the image css appears to resolve this issue

**Comment by lancesafranek** [comment]
Still an issue for cards resolving (from the stack). This did fix it for the battlefield.

**Comment by sjsafranek** [comment]
Will add the border-radius class to sweetalert card images

**Comment by sjsafranek** [comment]
a css class (mtg-card-image) has been added to sweetalert card images

**Comment by lancesafranek** [comment]
This has regressed.

**Comment by lancesafranek** [comment]
Clarification, this is still an issue only for tapped creatures.

**Comment by sjsafranek** [comment]
i am a little confused why this has happened to cards in the battlefield... I am not entirely sure how the svg clip is working in this regard

**Comment by sjsafranek** [comment]
svg 'clip-path: inset' property is now used. This seems to have fixed the issue
