### ISSUE TITLE
Selection Behaviour Not Clear

### ISSUE THREAD

**Issue by lancesafranek** [sjsafranek/mtghordesurvival#7]
Currently, it isn't clear what cards are selected. Selection should result in highlighting cards with a border (yellow?).

Card selection should obey these rules:
1. Clicking the battlefield (or anything except a card) should deselect all cards.
2. Selection should be additive, e.g. selecting a card when a few are already selected should add to the selection (as opposed to requiring to use a modifier, e.g. Shift + Click).
3. Game actions resulting from dragging should apply to all selected cards, e.g. dragging to the graveyard should destroy all selected cards.

**Comment by sjsafranek** [comment]
I changed the highlight color to pale green and fixed items 1 & 2.

**Comment by sjsafranek** [comment]
this should be fixed

**Comment by lancesafranek** [comment]
Selection is now clear, but isn't  additive for regular cards (it is additive for tokens)

**Comment by lancesafranek** [comment]
There's also a conflict between the attack border animation and the selection state. Can't tell what's selected while creatures are attacking.

**Comment by sjsafranek** [comment]
the card selection now work like they do in mtg arena
